// Regenerates src/Hubertech.Belgium/BankCodes.Generated.cs from the list of bank identification
// codes published by the National Bank of Belgium:
//
//   dotnet run tools/UpdateBankCodes.cs                downloads the current list
//   dotnet run tools/UpdateBankCodes.cs -- list.xlsx   reads a copy downloaded beforehand
//
// The tool stops, without writing anything, when the list does not look as expected: a code
// missing or listed twice, or a value that is neither a BIC nor a known placeholder.
using System.Globalization;
using System.IO.Compression;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

const string SourceUrl = "https://www.nbb.be/doc/be/be/protocol/grouped_list_current.xlsx";

// What the list writes instead of a BIC: free (VRIJ), or unavailable, or an institution without a BIC.
string[] placeholders = ["-", "N/A", "NAV", "NYA", "VRIJ"];

byte[] workbook = args.Length > 0
    ? await File.ReadAllBytesAsync(args[0])
    : await new HttpClient().GetByteArrayAsync(new Uri(SourceUrl));

List<string[]> rows = ReadFirstSheet(workbook);

DateOnly version = DateOnly.ParseExact(
    Regex.Match(rows[0][0], @"\d{2}/\d{2}/\d{4}").Value, "dd/MM/yyyy", CultureInfo.InvariantCulture);

if (rows[1] is not ["From", "To", "Biccode", ..])
{
    throw new InvalidDataException($"Unexpected header: {string.Join(" | ", rows[1])}");
}

var ranges = new List<(int First, int Last, string Bic)>();
int nextCode = 0;
foreach (string[] row in rows.Skip(2))
{
    int first = int.Parse(row[0], CultureInfo.InvariantCulture);
    int last = int.Parse(row[1], CultureInfo.InvariantCulture);
    if (first != nextCode || last < first)
    {
        throw new InvalidDataException($"Codes {row[0]} to {row[1]} do not follow code {nextCode - 1}.");
    }

    nextCode = last + 1;

    string value = row.Length > 2 ? row[2].Trim() : string.Empty;
    string bic = value.Replace(" ", string.Empty, StringComparison.Ordinal);
    if (Regex.IsMatch(bic, "^[A-Z]{4}BE[A-Z0-9]{2}([A-Z0-9]{3})?$"))
    {
        ranges.Add((first, last, bic));
    }
    else if (!placeholders.Contains(value, StringComparer.OrdinalIgnoreCase))
    {
        throw new InvalidDataException($"Codes {row[0]} to {row[1]}: '{value}' is neither a BIC nor a known placeholder.");
    }
}

if (nextCode != 1000)
{
    throw new InvalidDataException($"The list stops at code {nextCode - 1}.");
}

var source = new StringBuilder();
source.Append(CultureInfo.InvariantCulture, $$"""
    // <auto-generated>
    //     Generated by tools/UpdateBankCodes.cs from the list of bank identification codes of the
    //     National Bank of Belgium, version of {{version:yyyy-MM-dd}}:
    //     {{SourceUrl}}
    //     Do not edit this file: run the tool again.
    // </auto-generated>

    namespace Hubertech.Belgium;

    internal static partial class BankCodes
    {
        // The bank codes that have a BIC, in ascending order. The other codes have none.
        internal static readonly BankCodeRange[] Ranges =
        [

    """);
foreach (var (first, last, bic) in ranges)
{
    source.Append(CultureInfo.InvariantCulture, $"        new({first}, {last}, \"{bic}\"),\n");
}

source.Append("    ];\n}\n");

string output = Path.Combine(RepositoryRoot(), "src", "Hubertech.Belgium", "BankCodes.Generated.cs");
await File.WriteAllTextAsync(output, source.ToString());
Console.WriteLine($"{ranges.Count} ranges with a BIC, list of {version:yyyy-MM-dd}, written to {output}");

// The rows of the first worksheet, as text. An .xlsx file is a zip archive of XML parts.
static List<string[]> ReadFirstSheet(byte[] workbook)
{
    XNamespace main = "http://schemas.openxmlformats.org/spreadsheetml/2006/main";
    using var archive = new ZipArchive(new MemoryStream(workbook));

    XDocument Part(string name)
    {
        using Stream stream = (archive.GetEntry(name) ?? throw new InvalidDataException($"{name} is missing.")).Open();
        return XDocument.Load(stream);
    }

    string[] sharedStrings = [.. Part("xl/sharedStrings.xml").Root!.Elements(main + "si").Select(item => string.Concat(item.Descendants(main + "t").Select(text => text.Value)))];

    var rows = new List<string[]>();
    foreach (XElement row in Part("xl/worksheets/sheet1.xml").Root!.Descendants(main + "row"))
    {
        var cells = new List<string>();
        foreach (XElement cell in row.Elements(main + "c"))
        {
            // Empty cells are left out of the file: pad up to the column of this one.
            int column = ColumnIndex((string)cell.Attribute("r")!);
            while (cells.Count < column)
            {
                cells.Add(string.Empty);
            }

            string value = cell.Element(main + "v")?.Value ?? string.Empty;
            cells.Add((string?)cell.Attribute("t") == "s" ? sharedStrings[int.Parse(value, CultureInfo.InvariantCulture)] : value);
        }

        rows.Add([.. cells]);
    }

    return rows;
}

// The zero-based column of a cell reference such as C12.
static int ColumnIndex(string reference) =>
    reference.TakeWhile(char.IsAsciiLetterUpper).Aggregate(0, (index, letter) => (index * 26) + letter - 'A' + 1) - 1;

static string RepositoryRoot([System.Runtime.CompilerServices.CallerFilePath] string tool = "") =>
    Path.GetDirectoryName(Path.GetDirectoryName(tool))!;
